const express = require("express");
const router = express.Router();
const db = require("../db");

// ================= GET ALL CREDITS =================
router.get("/", (req, res) => {
  const sql = "SELECT * FROM credits ORDER BY id DESC";
  db.query(sql, (err, rows) => {
    if (err) {
      console.error("FETCH ERROR:", err);
      return res.status(500).json(err);
    }
    res.json(rows);
  });
});

// ================= ADD NEW CREDIT =================
router.post("/", (req, res) => {
  const { name, payment, credit } = req.body;

  if (!name || payment == null || credit == null) {
    return res.status(400).json({ message: "All fields required" });
  }

  // INSERT without remaining (generated by MySQL)
  const sql = `INSERT INTO credits (name, payment, credit) VALUES (?, ?, ?)`;

  db.query(sql, [name, payment, credit], (err, result) => {
    if (err) {
      console.error("INSERT ERROR:", err);
      return res.status(500).json(err);
    }

    // Return the inserted row
    db.query("SELECT * FROM credits WHERE id = ?", [result.insertId], (err2, rows) => {
      if (err2) return res.status(500).json(err2);
      res.json(rows[0]);
    });
  });
});

module.exports = router;